### ISSUE TITLE
下载zip格式的附件报错

### ISSUE THREAD

**Issue by yeminv** [zeemood/mail-plus#1]
你还，请问有没有遇到过下载zip格式附件报错的情况啊，microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. ParseError at [row,col]:[1,10706983]
Message: Premature end of file.
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,10706983]
Message: Premature end of file.
是((FileAttachment) attachment).load(file.getAbsolutePath()); 方法报错，用((FileAttachment) attachment).load(outputStream);方法也报同样的错误。下载excel基本不会出错。

**Comment by zeemood** [comment]
你好。这个可以考虑下文件的大小以及超时时间。你设置一下连接的超时时间。
